### ISSUE TITLE
undefined method `write_nonblock' for OpenSSL::SSL::SSLSocket

### ISSUE THREAD

**Issue by atambo** [jruby/jruby-ossl#19]
When I upgraded from jruby-openssl 0.7.4 to 0.7.6.1 I started getting this error when trying to do file uploads to amazon s3 using the fog gem:

https://gist.github.com/1694196
